In [1]:
dtype_dict = {'bathrooms':float, 'waterfront':int, 
              'sqft_above':int, 'sqft_living15':float, 'grade':int,
              'yr_renovated':int, 'price':float, 'bedrooms':float, 'zipcode':str, 
              'long':float, 'sqft_lot15':float, 'sqft_living':float, 'floors':str,
              'condition':int, 'lat':float, 'date':str, 'sqft_basement':int, 'yr_built':int,
              'id':str, 'sqft_lot':int, 'view':int}

In [2]:
import numpy as np
import pandas as pd

In [6]:
input_file = "kc_house_data.csv"
all_data = pd.read_csv(input_file, header = 0)
input_file = "kc_house_test_data.csv"
test_data = pd.read_csv(input_file, header = 0)
input_file = "kc_house_train_data.csv"
train_data = pd.read_csv(input_file, header = 0)

In [8]:
 from sklearn.linear_model import LinearRegression

In [9]:
train_data['bedrooms_squared'] = np.power(train_data['bedrooms'],2)

In [10]:
train_data['bedrooms_squared'] = np.power(train_data['bedrooms'],2)
train_data['bed_bath_rooms'] = train_data['bedrooms']*train_data['bathrooms']
train_data['log_sqft_living'] = np.log(train_data['sqft_living'])
train_data['lat_plus_long'] = train_data['lat']+train_data['long']

In [11]:
train_data.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  yr_renovated  zipcode      lat  \
0      5650     1.0           0     0  ...             0    98178  47.5112   
1      7242     2.0           0     0  ...          1991    98125  47.7210   
2     10000     1.0           0     0  ...             0    98028  47.7379   
3      5000     1.0           0     0  ...             0    98136  47.5208   
4      8080     1.0           0     0  ...             0    98074  47.6168   

      long  sqft_living15  sqft_lot15  bedrooms_squared  bed_bath_rooms  \
0 -122.257           1340        5650                 9            3.00   
1 -122.319           1690        7639                 9            6.75   
2 -122.233           2720        8062                 4            2.00   
3 -122.393           1360        5000                16           12.00   
4 -122.045           1800        7503                 9            6.00   

   log_sqft_living  lat_plus_long  
0         7.073270       -74.7458  
1         7.851661       -74.5980  
2         6.646391       -74.4951  
3         7.580700       -74.8722  
4         7.426549       -74.4282  

[5 rows x 25 columns]

In [12]:
test_data['bedrooms_squared'] = np.power(test_data['bedrooms'],2)
test_data['bed_bath_rooms'] = test_data['bedrooms']*test_data['bathrooms']
test_data['log_sqft_living'] = np.log(test_data['sqft_living'])
test_data['lat_plus_long'] = test_data['lat']+test_data['long']
test_data.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0   114101516  20140528T000000  310000.0         3        1.0         1430   
1  9297300055  20150124T000000  650000.0         4        3.0         2950   
2  1202000200  20141103T000000  233000.0         3        2.0         1710   
3  8562750320  20141110T000000  580500.0         3        2.5         2320   
4  7589200193  20141110T000000  535000.0         3        1.0         1090   

   sqft_lot  floors  waterfront  view  ...  yr_renovated  zipcode      lat  \
0     19901     1.5           0     0  ...             0    98028  47.7558   
1      5000     2.0           0     3  ...             0    98126  47.5714   
2      4697     1.5           0     0  ...             0    98002  47.3048   
3      3980     2.0           0     0  ...             0    98027  47.5391   
4      3000     1.5           0     0  ...             0    98117  47.6889   

      long  sqft_living15  sqft_lot15  bedrooms_squared  bed_bath_rooms  \
0 -122.229           1780       12697                 9             3.0   
1 -122.375           2140        4000                16            12.0   
2 -122.218           1030        4705                 9             6.0   
3 -122.070           2580        3980                 9             7.5   
4 -122.375           1570        5080                 9             3.0   

   log_sqft_living  lat_plus_long  
0         7.265430       -74.4732  
1         7.989560       -74.8036  
2         7.444249       -74.9132  
3         7.749322       -74.5309  
4         6.993933       -74.6861  

[5 rows x 25 columns]

In [13]:
np.average(test_data['bedrooms_squared'])

12.4466777015843

In [14]:
np.average(test_data["bed_bath_rooms"])

7.5039016315913925

In [15]:
np.average(test_data["log_sqft_living"])

7.550274679645938

In [16]:
np.average(test_data["lat_plus_long"])

-74.65333355403168

In [53]:
model=LinearRegression(fit_intercept=True, normalize=False, copy_X=True, n_jobs=None)

In [74]:
m1_data=train_data[["sqft_living", "bedrooms", "bathrooms","lat", "long"]]
m1_data_target=train_data[["price"]]
model1= model.fit(m1_data,m1_data_target)
#model1= model.fit(train_data["sqft_living","bedrooms"],train_data['price'])

In [75]:
print(model1.coef_)

[[ 3.12258646e+02 -5.95865332e+04  1.57067421e+04  6.58619264e+05
  -3.09374351e+05]]


In [76]:
m2_data=train_data[["sqft_living", "bedrooms", "bathrooms","lat", "long","bed_bath_rooms"]]
m2_data_target=train_data[["price"]]
model2= model.fit(m2_data,m2_data_target)

In [77]:
print(model2.coef_)

[[ 3.06610053e+02 -1.13446368e+05 -7.14613083e+04  6.54844630e+05
  -2.94298969e+05  2.55796520e+04]]


In [78]:
m3_data=train_data[["sqft_living", "bedrooms", "bathrooms","lat", "long","bed_bath_rooms","log_sqft_living","bedrooms_squared"]]
m3_data_target=train_data[["price"]]
model3= model.fit(m3_data,m3_data_target)

In [79]:
print(model3.coef_)

[[ 5.29422820e+02  3.45142296e+04  6.70607813e+04  6.61420511e+05
  -2.79415811e+05 -8.57050439e+03 -5.61831484e+05 -6.78858667e+03]]


In [81]:
model1.residues_

AttributeError: 'LinearRegression' object has no attribute 'residues_'

In [87]:
train_matrix1= np.array(train_data)

In [88]:
train_matrix1

array([[7129300520, '20141013T000000', 221900.0, ..., 3.0,
        7.07326971745971, -74.7458],
       [6414100192, '20141209T000000', 538000.0, ..., 6.75,
        7.851661177889265, -74.598],
       [5631500400, '20150225T000000', 180000.0, ..., 2.0,
        6.646390514847729, -74.49509999999998],
       ...,
       [263000018, '20140521T000000', 360000.0, ..., 7.5,
        7.333023014386481, -74.64670000000001],
       [291310100, '20150116T000000', 400000.0, ..., 7.5,
        7.3777589082278725, -74.53450000000001],
       [1523300157, '20141015T000000', 325000.0, ..., 1.5,
        6.927557906278317, -74.7049]], dtype=object)

In [89]:
def get_numpy_data(data_sframe, features, output):
    data_sframe['constant'] = 1 # add a constant column to an SFrame
    # prepend variable 'constant' to the features list
    features = ['constant'] + features
    # select the columns of data_SFrame given by the ‘features’ list into the SFrame ‘features_sframe’
    features_sframe=data_sframe[features]
    # this will convert the features_sframe into a numpy matrix:
    features_matrix = np.array(features_sframe)
    # assign the column of data_sframe associated with the target to the variable ‘output_sarray’
    output_sarray=data_sframe[output]
    # this will convert the SArray into a numpy array:
    output_array = np.array(output_sarray)
    return(features_matrix, output_array)


In [90]:
def predict_outcome(feature_matrix, weights):
    predictions=np.dot(feature_matrix,weights)
    return(predictions)


In [98]:
def feature_derivative(errors, feature):
    derivative=np.dot(errors,feature)
    return(2*derivative)

In [102]:
from math import sqrt

def regression_gradient_descent(feature_matrix, output, initial_weights, step_size, tolerance):
    converged = False
    
    weights = np.array(initial_weights)
    while not converged:
        # compute the predictions based on feature_matrix and weights:
        predictions = predict_outcome(feature_matrix, weights)
    
        # compute the errors as predictions - output:
        errors = predictions - output
        gradient_sum_squares = 0 # initialize the gradient
        # while not converged, update each weight individually:
        for i in range(len(weights)):
            # Recall that feature_matrix[:, i] is the feature column associated with weights[i]
            # compute the derivative for weight[i]:
            derivative = feature_derivative(errors, feature_matrix[:, i])
            # add the squared derivative to the gradient magnitude
            gradient_sum_squares += np.power(derivative, 2)
            # update the weight based on step size and derivative:
            weights[i] -= step_size * derivative
            
        gradient_magnitude = sqrt(gradient_sum_squares)
        if gradient_magnitude < tolerance:
            converged = True
    return(weights)


In [103]:
simple_features = ['sqft_living']
my_output= 'price'
(simple_feature_matrix, output) = get_numpy_data(train_data, simple_features, my_output)
initial_weights = np.array([-47000., 1.])
step_size = 7e-12
tolerance = 2.5e7

In [105]:
simple_weights = regression_gradient_descent(simple_feature_matrix, output,initial_weights, step_size, tolerance)

In [106]:
simple_weights

array([-46999.88716555,    281.91211918])

In [107]:
(test_simple_feature_matrix, test_output) = get_numpy_data(test_data, simple_features, my_output)


In [109]:
test_simple_predictions = predict_outcome(test_simple_feature_matrix, simple_weights)


In [110]:
test_simple_predictions

array([356134.443255  , 784640.86440132, 435069.83662406, ...,
       663418.65315598, 604217.10812919, 240550.47439317])

In [122]:
test_simple_residuals = test_simple_predictions - test_data['price']
test_simple_rss = sum(pow(test_simple_residuals,2))
print(test_simple_rss)

275400044902128.78


In [112]:
model_features = ['sqft_living', 'sqft_living15']
my_output = 'price'
(feature_matrix, output) = get_numpy_data(train_data, model_features,my_output)
initial_weights = np.array([-100000., 1., 1.])
step_size = 4e-12

tolerance = 1e9
simple_weights2 = regression_gradient_descent(feature_matrix, output,initial_weights, step_size, tolerance)

In [113]:
simple_weights2

array([-9.99999688e+04,  2.45072603e+02,  6.52795267e+01])

In [115]:
test_simple_predictions2 = predict_outcome(feature_matrix, simple_weights2)
test_simple_predictions2

array([276660.26901584, 640159.02217622, 266266.24843983, ...,
       374838.79030123, 384160.32933988, 216559.20391786])

In [120]:
 test_data['price'][0]-test_simple_predictions2[0]

33339.73098416184

In [119]:
test_data['price'][0]-test_simple_predictions[0]

-46134.44325500238

In [123]:
test_simple_residuals2 = test_simple_predictions2 - test_data['price']
test_simple_rss2 = sum(pow(test_simple_residuals2,2))
print(test_simple_rss2)

ValueError: operands could not be broadcast together with shapes (17384,) (4229,) 